name: CI - Test Alfresco Ubuntu Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu:24.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Run Alfresco Installer Script
      run: |
        sudo useradd -m ubuntu
        bash scripts/01-install_postgres.sh
        bash scripts/02-install_java.sh
        bash scripts/03-install_tomcat.sh
        bash scripts/04-install_activemq.sh
        bash scripts/05-download_alfresco_resources.sh
        bash scripts/06-install_alfresco.sh
        bash scripts/07-install_solr.sh
        bash scripts/08-install_transform.sh
        bash scripts/09-build_aca.sh
        bash scripts/10-install_nginx.sh

    - name: Verify Alfresco Installation as ubuntu user
      run: |
        systemctl status alfresco